### ISSUE TITLE
Realizar el Script de volcado de datos sobre la BBDD

### ISSUE THREAD

**Issue by RubenGonz** [RubenGonz/PokemonDb#11]
#11 Hay que hacer todas las inserciones en la base de datos de todas las correspondientes tablas

**Comment by jpexposito** [comment]
Esta tarea se debería de llamar realizar el Script de volcado de datos sobre la BBDD

**Comment by amarzar** [comment]
Como les he comentado hay que buscar la forma de automatizar la carga de datos en cada una de las tablas. Se trata de optimizar.
